#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
科技 × 金融早报自动生成脚本

功能：
1. 每日自动更新早报日期
2. 生成历史存档页面
3. 支持接入外部新闻 API 扩展（可选）

使用方式：
    python scripts/generate_brief.py

环境变量（可选）：
    - NEWS_API_KEY: 新闻 API 密钥（用于获取实时新闻）
    - TZ: 时区设置，默认为 Asia/Shanghai
"""

import os
import sys
import json
import shutil
from datetime import datetime, timezone, timedelta
from pathlib import Path

# 设置时区
TZ = os.environ.get('TZ', 'Asia/Shanghai')
if TZ == 'Asia/Shanghai':
    tz = timezone(timedelta(hours=8))
else:
    tz = timezone.utc

# 项目根目录
ROOT_DIR = Path(__file__).parent.parent
INDEX_HTML = ROOT_DIR / 'index.html'
ARCHIVE_DIR = ROOT_DIR / 'archive'


def get_today_str():
    """获取今日日期字符串"""
    today = datetime.now(tz)
    return today.strftime('%Y-%m-%d')


def get_today_display():
    """获取今日日期显示格式"""
    today = datetime.now(tz)
    weekdays = ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日']
    weekday = weekdays[today.weekday()]
    return today.strftime(f'%Y年%m月%d日 {weekday} · 北京时间 08:00 更新')


def generate_archive():
    """生成历史存档文件"""
    today_str = get_today_str()
    
    # 创建存档目录
    ARCHIVE_DIR.mkdir(exist_ok=True)
    
    # 复制今日早报到存档
    archive_file = ARCHIVE_DIR / f'morning-brief-{today_str}.html'
    if INDEX_HTML.exists() and not archive_file.exists():
        shutil.copy2(INDEX_HTML, archive_file)
        print(f'✓ 已创建存档: {archive_file.name}')
    
    # 生成存档列表页面
    generate_archive_index()


def generate_archive_index():
    """生成存档索引页面"""
    archive_files = sorted(ARCHIVE_DIR.glob('morning-brief-*.html'), reverse=True)
    
    html_content = f'''<!-- Generated by Trae Work -->
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>历史存档 - 科技 × 金融早报</title>
<style>
  :root{{
    --bg:#f6f8fb; --card:#ffffff; --ink:#1a2330; --sub:#5b6b7e;
    --line:#e7ecf2; --accent:#1f6feb;
  }}
  *{{box-sizing:border-box;margin:0;padding:0}}
  body{{font-family:-apple-system,BlinkMacSystemFont,"PingFang SC","Microsoft YaHei",sans-serif;
    background:var(--bg);color:var(--ink);line-height:1.7;padding:24px 16px;max-width:880px;margin:0 auto}}
  h1{{font-size:26px;font-weight:800;letter-spacing:.5px;margin-bottom:6px}}
  .lead{{color:var(--sub);margin-bottom:22px;font-size:14px}}
  .card{{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:20px 22px;margin:16px 0;box-shadow:0 1px 3px rgba(0,0,0,.04)}}
  h2{{font-size:19px;margin:0 0 12px;padding-left:11px;border-left:5px solid var(--accent);font-weight:800}}
  .archive-list{{list-style:none}}
  .archive-list li{{padding:12px 0;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center}}
  .archive-list li:last-child{{border-bottom:none}}
  .archive-list a{{color:var(--accent);text-decoration:none;font-weight:600}}
  .archive-list a:hover{{text-decoration:underline}}
  .date-tag{{font-size:12px;color:var(--sub);background:#f0f4f9;padding:2px 10px;border-radius:12px}}
  .back-link{{margin-bottom:20px}}
  .back-link a{{color:var(--accent);text-decoration:none;font-size:14px}}
  .back-link a:hover{{text-decoration:underline}}
  footer{{margin-top:26px;font-size:12.5px;color:var(--sub);border-top:1px solid var(--line);padding-top:14px;line-height:1.8}}
</style>
</head>
<body>

<div class="back-link">
  <a href="../index.html">← 返回今日早报</a>
</div>

<h1>📚 早报历史存档</h1>
<p class="lead">共 {len(archive_files)} 期历史早报，点击查看往期内容。</p>

<div class="card">
  <h2>全部存档</h2>
  <ul class="archive-list">
'''
    
    for i, f in enumerate(archive_files):
        date_str = f.stem.replace('morning-brief-', '')
        try:
            date_obj = datetime.strptime(date_str, '%Y-%m-%d')
            display_date = date_obj.strftime('%Y年%m月%d日')
            weekdays = ['周一', '周二', '周三', '周四', '周五', '周六', '周日']
            weekday = weekdays[date_obj.weekday()]
            label = '最新' if i == 0 else ''
        except:
            display_date = date_str
            weekday = ''
            label = ''
        
        html_content += f'''    <li>
      <a href="{f.name}">{display_date} {weekday} 早报</a>
      <span class="date-tag">{label or date_str}</span>
    </li>
'''
    
    html_content += '''  </ul>
</div>

<footer>
  <p>📋 本页面由 GitHub Actions 自动生成，每日更新。</p>
  <p>⚠️ 免责声明：早报内容仅供信息参考，不构成任何投资建议。</p>
</footer>

</body>
</html>
'''
    
    archive_index = ARCHIVE_DIR / 'index.html'
    archive_index.write_text(html_content, encoding='utf-8')
    print(f'✓ 已更新存档索引: {archive_index.name}')


def update_index_date():
    """更新 index.html 中的日期"""
    if not INDEX_HTML.exists():
        print(f'✗ 未找到 {INDEX_HTML}')
        return False
    
    content = INDEX_HTML.read_text(encoding='utf-8')
    today_display = get_today_display()
    
    # 替换日期显示
    import re
    # 匹配日期行
    pattern = r'<p class="date" id="brief-date">.*?</p>'
    replacement = f'<p class="date" id="brief-date">{today_display}</p>'
    
    new_content = re.sub(pattern, replacement, content)
    
    if new_content != content:
        INDEX_HTML.write_text(new_content, encoding='utf-8')
        print(f'✓ 已更新日期: {today_display}')
        return True
    else:
        print('ℹ 日期已是最新')
        return False


def main():
    """主函数"""
    print('=' * 50)
    print('☀️  科技 × 金融早报自动生成器')
    print('=' * 50)
    print(f'今日日期: {get_today_display()}')
    print()
    
    # 1. 更新首页日期
    print('[1/3] 更新早报日期...')
    updated = update_index_date()
    
    # 2. 生成存档
    print()
    print('[2/3] 生成历史存档...')
    generate_archive()
    
    # 3. 完成
    print()
    print('[3/3] 生成完成！')
    print()
    print('📌 后续可扩展：')
    print('   - 接入新闻 API 获取实时数据')
    print('   - 接入 AI 模型生成个性化分析')
    print('   - 添加更多市场数据看板')
    print()
    print('✅ 早报生成完毕，可以部署了！')


if __name__ == '__main__':
    main()
